document.write('          <div class="navbar-default sidebar" role="navigation">                                                                              ');
    document.write('             <div class="sidebar-nav navbar-collapse">                                                                                     ');
      document.write('               <ul class="nav" id="side-menu">                                                                                           ');
 document.write('                        <li class="sidebar-search">                                                                                           ');
 document.write('                            <div class="input-group custom-search-form">                                                                      ');
 document.write('                                <input type="text" class="form-control" placeholder="Search...">                                              ');
 document.write('                                <span class="input-group-btn">                                                                                ');
 document.write('                                <button class="btn btn-default" type="button">                                                                ');
 document.write('                                    <i class="fa fa-search"></i>                                                                              ');
 document.write('                                </button>                                                                                                     ');
 document.write('                            </span>                                                                                                           ');
 document.write('                            </div>                                                                                                            ');
 document.write('                            <!-- /input-group -->                                                                                             ');
 document.write('                        </li>                                                                                                                 ');
 document.write('                        <li>                                                                                                                  ');
 document.write('                            <a href="index.html"><i class="fa fa-dashboard  fa-fw"></i> 首页</a>                                               ');
 document.write('                        </li>   	       ');
 document.write('                        <li>                                                                                                                  ');
 document.write('                            <a href="tables.html"><i class="fa fa-table fa-fw"></i> 物业<span class="fa arrow"></a>                           ');
 document.write('                            <ul class="nav nav-second-level in">                                                                              ');
 document.write('                                <li>                                                                                                          ');
 document.write('                                    <a  href="入住率.html">入住率</a>                                                                         ');
 document.write('                                </li>                                                                                                         ');
 document.write('                                <li>                                                                                                          ');
 document.write('                                    <a  href="入住率-钻取-房产状态.html">入住率-钻取-房产状态</a>                                             ');
 document.write('                                </li>                                                                                                         ');
 document.write('                                <li><a  href="房产状态统计_户数.html">房产状态统计_户数</a></li>                                              ');
 document.write('                                <li><a  href="房产状态统计_面积.html">房产状态统计_面积</a></li>                                              ');
 document.write('                                <li>                                                                                                          ');
 document.write('                                    <a   href="经营能力.html">经营能力</a>                                                                    ');
 document.write('                                </li>   <li><a href="index_area.html"> 区块报表</a></li>                                                                                                      ');
 document.write('                                                                                                                                              ');
 document.write('                                                                                                                                              ');
 document.write('                            </ul>                                                                                                             ');
 document.write('                        </li>                                                                                                                 ');
 document.write('                        <li>                                                                                                                  ');
 document.write('                            <a href="forms.html"><i class="fa fa-edit fa-fw"></i>财务<span class="fa arrow"></a>                              ');
 document.write('                            <ul class="nav nav-second-level in">                                                                              ');
 document.write('                                <li>                                                                                                          ');
 document.write('                                    <a href="收费率.html" > 收费率 </a>                                                                       ');
 document.write('                                </li>                                                                                                         ');
 document.write('                                                                                                                                              ');
 document.write('                                <li>                                                                                                          ');
 document.write('                                    <a href="收费率-钻取-收费台帐.html" >收费率-钻取-收费台帐</a>                                             ');
 document.write('                                </li>                                                                                                         ');
 document.write('                                <li>                                                                                                          ');
 document.write('                                    <a href="收费率-钻取-费用组成.html" >收费率-钻取-费用组成</a>                                             ');
 document.write('                                </li>                                                                                                         ');
 document.write('                                                                                                                                              ');
 document.write('                                 <li>                                                                                                         ');
 document.write('                                    <a href="欠费面积.html" > 欠费面积 </a>                                                                   ');
 document.write('                                </li>                                                                                                         ');
 document.write('                                                                                                                                              ');
 document.write('                                 <li>                                                                                                         ');
 document.write('                                    <a href="欠费户数.html" > 欠费户数 </a>                                                                   ');
 document.write('                                </li>                                                                                                         ');
 document.write('                                                                                                                                              ');
 document.write('                            </ul>                                                                                                             ');
 document.write('                        </li>                                                                                                                 ');
 document.write('                        <li>                                                                                                                  ');
 document.write('                            <a href="#"><i class="fa fa-wrench fa-fw"></i> 经营<span class="fa arrow"></span></a>                             ');
 document.write('                        </li>                                                                                                                 ');
 document.write('                        <li>                                                                                                                  ');
 document.write('                            <a href="#"><i class="fa fa-sitemap fa-fw"></i>客户<span class="fa arrow"></span></a>                             ');
 document.write('                        </li>                                                                                                                 ');
 document.write('                                                                                                                                              ');
 document.write('                         <li>                                                                                                                 ');
 document.write('                            <a href="#"><i class="fa fa-sitemap fa-fw"></i>其他<span class="fa arrow"></span></a>                             ');
 document.write('                            <ul class="nav nav-second-level in">                                                                              ');
 document.write('                                 <li>                                                                                                         ');
 document.write('                                    <a   href="友邻APP登录数据点.html">友邻APP登录数据点</a>                                                  ');
 document.write('                                </li>                                                                                                         ');
 document.write('                                                                                                                                              ');
 document.write('                            </ul>                                                                                                             ');
 document.write('                        </li>                                                                                                                 ');
 document.write('                                                                                                                                              ');
 document.write('                    </ul>                                                                                                                     ');
 document.write('                </div>                                                                                                                        ');
 document.write('                <!-- /.sidebar-collapse -->                                                                                                   ');
 document.write('            </div>                                                                                                                            ');